version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      default:
        aliases:
          - redis
    ports:
      - "6379:6379"
