services:
  waifuvault:
    image: simonmcnair/waifuvault:main

    environment:
      - http_proxy
      - https_proxy
      - no_proxy

    restart: always
    ports:
      - "8081:8081"
    stdin_open: true  # -i
    tty: true         # -t
