services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      default:
        aliases:
          - redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres
    ports:
      - "5004:5432"

volumes:
  postgres_data:
