on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install required packages for building the thumbnails module
      - name: Install libvips dependencies for thumbnails
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev build-essential

      # Setup Go for building Go modules
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Build the thumbnails module with CGO enabled
      - name: Build thumbnails
        run: |
          cd go/thumbnails
          CGO_ENABLED=1 go build .

      # Build the zipFiles module
      - name: Build zipFiles
        run: |
          cd go/zipFiles
          go build .

      # Node.js steps
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true
      - name: install
        run: npm install
      - name: TSC
        run: npm run tsc
      - name: ESLint
        run: npm run lint
      - name: prettier
        run: npm run prettier
      - name: compile
        run: npm run build
      - name: migration
        run: npm run runmigration:ci
      - name: Create files folder
        run: mkdir -p files
      - name: start-test
        run: npm run start_js:ci