on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true
      - name: install
        run: npm install
      - name: TSC
        run: npm run tsc
      - name: ESLint
        run: npm run lint
      - name: prettier
        run: npm run prettier
      - name: compile
        run: npm run build
      - name: migration
        run: npm run runmigration:ci
      - name: Create files folder
        run: mkdir -p files
      - name: start-test
        run: npm run start_js:ci
